### ISSUE TITLE
Run SLDP with hg38

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/sldp#1]
Hi,

Thanks for the great package however I'm running into difficulties running SLDP on summary statistics data aligned to the hg38 reference genome. Specifically, is there a hg38 version of the pickrell_ldblocks.hg19.eur.bed file, downloaded from:

https://data.broadinstitute.org/alkesgroup/SLDP/refpanel/pickrell_ldblocks.hg19.eur.bed

Is there any other files I would need to change to hg38 versions to run?

Thanks,
Alan.

**Comment by yakirr** [comment]
Hi Alan,

Thank you for the kind words! We haven't made an hg38 version of this file ourselves. You could consider using liftover to convert the coordinates in this file. Or alternatively, you could email Pickrell et al to ask if they've created one for hg38.

To run sldp with hg38, I believe you'll also need to map the reference panel to hg38 and then re-process it.

(If you're looking for a quick fix, it might overall be easier to map your summary statistics and annotations of interest to hg19?)

Yakir

**Comment by Al-Murphy** [comment]
Hey Yakir,

Thank you for your reply and thoughts on this. I have since emailed Pickrell et al so hopefully something will come of that.

I think your suggested quick fix will be good for now but long term, I will try lifting everything over. On that, for lifting over the reference panel, are the instructions to reprocess it given in the documentation? Sorry, I can't seem to find it.

Thanks,
Alan.

**Comment by yakirr** [comment]
Hi Alan,

The instructions for pre-processing, including reference panels, are here:
https://github.com/yakirr/sldp/wiki/Preprocessing-instructions

Hope this helps,
Yakir

**Comment by Al-Murphy** [comment]
Hi Yakir,

Thanks for this, unfortunately I can't seem to get the code to run to preprocess the reference panel (even without using the lifted over files). See below:
```
(sldp) -bash-4.2$ ls
1000G_hm3_noMHC.rsid  pickrell_ldblocks.hg19.eur.bed  plink_files
(sldp) -bash-4.2$ preprocessrefpanel --svd-stem svds_95percent     --bfile-chr plink_files/1000G.EUR.QC.     --print-snps 1000G_hm3_noMHC.rsid     --ld-blocks pickrell_ldblocks.hg19.eur.bed
=====
/rds/general/user/aemurphy/home/anaconda3/envs/sldp/bin/preprocessrefpanel --svd-stem svds_95percent --bfile-chr plink_files/1000G.EUR.QC. --print-snps 1000G_hm3_noMHC.rsid --ld-blocks pickrell_ldblocks.hg19.eur.bed
=====
bfile_chr                plink_files/1000G.EUR.QC.
chroms                   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
config                   None
ld_blocks                pickrell_ldblocks.hg19.eur.bed
print_snps               1000G_hm3_noMHC.rsid
spectrum_percent         95
svd_stem                 svds_95percent
=====
Traceback (most recent call last):
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/bin/preprocessrefpanel", line 112, in <module>
    main(args)
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/bin/preprocessrefpanel", line 17, in main
    fs.makedir_for_file(args.svd_stem)
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/lib/python2.7/site-packages/ypy/fs.py", line 11, in makedir_for_file
    makedir(os.path.dirname(path_to_file))
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/lib/python2.7/site-packages/ypy/fs.py", line 7, in makedir
    os.makedirs(path_to_dir)
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```
I have also tried it when I created an empty folder named svds_95percent in the working directory but it still won't run. Any idea what the issue could be here?

Thanks,
Alan.

**Comment by yakirr** [comment]
Hi Alan,

I'm not really sure why so many small things are off here -- thank you for
your patience working through them!

Can you try running the command with '--svd-stem svds_95percent
./svds_95percent' instead of '--svd-stem svds_95percent svds_95percent' and
telling me if that fixes the problem for you?

Yakir

**Comment by Al-Murphy** [comment]
Hi Yakir,

`--svd-stem ./svds_95percent` sorted it, thanks for the suggestion!

If you don't mind, I just want to talk through the reference panel files that I think need to be lifted over, it would be great if you could confirm? I believe the following should be lifted over:

 * maf5 files in the format 'N.sannot.gz'
 * pickrell_ldblocks.hg19.eur.bed

While it isn't necessary to liftover: 

 * 1000G_hm3_noMHC.rsid (only rsids which don't change across genome builds)
 * CD.KG3.95
 * maf5 files in the format N.RV.gz (only contains RSID and major minor alleles not position)

I was going to use the weights data from [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6133304/) rather than lifting over the hg19 LD scores. They are given [here](https://alkesgroup.broadinstitute.org/LDSCORE/GRCh38/), the weights.tgz file. I also planned to use the plink files from that paper instead of lifting over the 1000G.EUR.QC.N.* files. Do you think that would work? The 1000G.EUR.QC.hm3_noMHC.N.* files don't seem to be available though so that is an issue.

Once this is done, I'll run the preprocessing scripts to create the hg38 svds_95percent. Does that all sound okay?

Thanks,
Alan.

**Comment by yakirr** [comment]
Hi Alan,

- I would re-generate the maf5 files in the format N.RV.gz once you've
lifted over the maf5 files themselves, because alleles may shift between LD
blocks when you move to a different genome build and the RV.gz format won't
know about this change.
- I think using the weights from Gazal et al is reasonable, just make sure
that the new weights file and the 1000G_hm3_noMHC.rsid file have the same
set of SNPs.
- I think using the plink files from Gazal et al is also okay; you can
generate the 1000G.EUR.QC.hm3_noMHC.N.* files by filtering with plink
<https://www.cog-genomics.org/plink/2.0/filter#variant> to the SNPs in
1000G_hm3_noMHC.rsid. Does that make sense?

Warmly,
Yakir
