### ISSUE TITLE
reference and minimal example data has been removed

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/sldp#11]
Hi it appears the reference panel data and minimal example data is no longer available at the address given on the github:

```
wget https://data.broadinstitute.org/alkesgroup/SLDP/sumstats/complex/CD.tar.gz &&
> tar -zxf CD.tar.gz &&
> rm CD.tar.gz
--2023-03-21 13:12:39--  https://data.broadinstitute.org/alkesgroup/SLDP/sumstats/complex/CD.tar.gz
Resolving data.broadinstitute.org (data.broadinstitute.org)... 69.173.92.29
Connecting to data.broadinstitute.org (data.broadinstitute.org)|69.173.92.29|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://alkesgroup.broadinstitute.org/SLDP/sumstats/complex/CD.tar.gz [following]
--2023-03-21 13:12:40--  https://alkesgroup.broadinstitute.org/SLDP/sumstats/complex/CD.tar.gz
Resolving alkesgroup.broadinstitute.org (alkesgroup.broadinstitute.org)... 34.120.167.96
Connecting to alkesgroup.broadinstitute.org (alkesgroup.broadinstitute.org)|34.120.167.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-21 13:12:40 ERROR 404: Not Found.
```

Navigating to `https://data.broadinstitute.org/alkesgroup/`, it appears the entire `SLDP` subfolder has been removed.

**Comment by yakirr** [comment]
Hi there,

Thanks for bringing this to our attention. We're looking into it and will get back to you!

**Comment by yakirr** [comment]
Dear Al-Murphy,

We've just moved the files relevant to the minimal working example back to a free directory, so the commands listed on the wiki should now work. Are you now able to run the MWE?

Yakir

**Comment by Al-Murphy** [comment]
Thanks very much for this, I appreciate it and that you have taken on the cost of sharing the minimal example. I know once publications are made, funding to keep such things going are not easy to come by! Yep running now, thanks again!
