### ISSUE TITLE
name 'reduce' is not defined

### ISSUE THREAD

**Issue by LeoJiny** [yakirr/sldp#14]
I am trying to use the SLDP package for my own analysis, but I have encountered an issue when running the minimal example provided in the documentation. When running the minimal example with python version 3.10 , I received the error:
![image](https://github.com/user-attachments/assets/b8a48f5a-63a4-4ca2-92bc-1815951f2cc1)

To troubleshoot, I created a new environment with Python 3.7 and ran “pip install sldp”. However, the installation did not complete successfully, and I encountered the following error:
 
![image](https://github.com/user-attachments/assets/3bf974f8-b97e-4deb-af61-683ce4b3d037)

I would be deeply grateful for your guidance and assistance in resolving this issue.

**Comment by yakirr** [comment]
Hi Leo, I wanted to thank you for the bugfixes you provided via personal communication - I've now implemented them in the relevant repos and have pushed new packages to pypi for ypy, gprim, and sldp.
