### ISSUE TITLE
how to create eas version pickrell_ldblocks.hg19.eur.bed file

### ISSUE THREAD

**Issue by AbbyD99** [yakirr/sldp#3]
Hi,

Thanks for the great package. I have a question about how pickrell_ldblocks.hg19.eur.bed file was created, I cannot understand the content of this file. I need to create an EAS VERSION of this file and don't know what to do.

Abby

**Comment by yakirr** [comment]
Hi Abby,

Thank you for the kind words! The file contains a list of LD blocks that sldp considers to be independent of each other. It's one line per LD block with zero-indexed genomic coordinates describing the start and end of that LD block. For example, the first few lines are

chr1	0	10583
chr1	10583	1892607
chr1	1892607	3582736

This means that the first LD block goes from position 1 to 10582 (inclusive) along chr1. The second LD block starts at 10583 and goes through 1892606 (inclusive). Etc.

I believe there are EAS versions of the Pickrell et al. LD blocks out there, see, e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4731402/

Hope this helps,
Yakir
