### ISSUE TITLE
how to make the EAS backgroundannots in maf5

### ISSUE THREAD

**Issue by AbbyD99** [yakirr/sldp#5]
Hi yakir,

I did what you suggested, there are no nans. I read the code in sldp, I think the problem is the maf5 backgroundannots I used, I think it's not for the EAS since the snps are not the same with my RV.gz and ref bim file. Can you tell me how to make the EAS backgroundannots in maf5?

Abby

**Comment by yakirr** [comment]
addressed in [https://github.com/yakirr/sldp/issues/4](issue 4).
